language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
  - clang

env:
  - BTYPE="Debug"
  - BTYPE="Release"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y lcov
  # install gcc 4.8 and update alternatives
  - if [ ${CXX} = "g++" ]; then sudo apt-get install -y gcc-4.8 g++-4.8; fi
  - if [ ${CXX} = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  # install CMake 3.2.2
  - curl http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz | tar -xzf -
  - cd cmake-3.2.2
  - (./bootstrap && sudo make install -j6) &> /dev/null
  - cd ../ && rm -fr cmake-3.2.2

script:
  - echo y | tools/build $BTYPE

after_success:
  - tools/test_on_install ${BTYPE}
  - tar -czf cbase_${TRAVIS_OS_NAME}_${CXX}_${BTYPE}.tar.gz install/

deploy:
  provider: releases
  api_key: "0caefc8639446abb10516ae70eb7defe654bf8d1"
  file: "cbase_${TRAVIS_OS_NAME}_${CXX}_${BTYPE}.tar.gz"
  skip_cleanup: true
  on:
    branch: develop
    tags: true

