# branches to build
branches:
  # whitelist
  only:
    - develop

environment:
  PROJ: "c:/projects/cbase"

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build:
  # path to Visual Studio solution or project
  project: c:/projects/cbase/build/check_on_install.vcxproj

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd /d %PROJ%
  - mkdir build
  - cd build
  - cmd: if "%platform%"=="x86" cmake -G"Visual Studio 12"  ..
  - cmd: if "%platform%"=="x64" cmake -G"Visual Studio 12 Win64" ..

after_build:
  - 7z a cbase_%configuration%_%platform%.zip %PROJ%/install
  - appveyor PushArtifact cbase_%configuration%_%platform%.zip
