# branches to build
branches:
  # whitelist
  only:
    - develop

environment:
  PROJ: "c:/projects/cbase"

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build:
  # path to Visual Studio solution or project
  project: c:/projects/cbase/build/check_on_install.vcxproj

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd /d %PROJ%
  - mkdir build
  - cd build
  - cmd: if "%platform%"=="x86" cmake -G"Visual Studio 12"  ..
  - cmd: if "%platform%"=="x64" cmake -G"Visual Studio 12 Win64" ..

after_build:
  - 7z a cbase_win_%configuration%_%platform%.zip %PROJ%/install
  - appveyor PushArtifact cbase_win_%configuration%_%platform%.zip

deploy:
  release: cbase-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: 0caefc8639446abb10516ae70eb7defe654bf8d1 # your encrypted token from GitHub
  artifact: cbase_win_%configuration%_%platform%.zip
  draft: false
  prerelease: false
  on:
    branch: develop                 # release from master branch only
    appveyor_repo_tag: true         # deploy on tag push only
