/*
Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by this 
license (the "Software") to use, reproduce, display, distribute, execute, and 
transmit the Software, and to prepare derivative works of the Software, and to 
permit third-parties to whom the Software is furnished to do so, all subject to the 
following:

The copyright notices in the Software and this entire statement, including the 
above license grant, this restriction and the following disclaimer, must be 
included in all copies of the Software, in whole or in part, and all derivative 
works of the Software, unless such copies or derivative works are solely in the 
form of machine-executable object code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT 
HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER 
LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/**
 * \file ints.h
 * \date 2015
 */

#ifndef CBASE_INTS_H
#define CBASE_INTS_H

#include <cbase/buildsym.h>


typedef char                cb_char;
typedef unsigned char       cb_uchar;
typedef char                cb_int8;
typedef unsigned char       cb_uint8;
typedef short               cb_int16;
typedef unsigned short      cb_uint16;
typedef unsigned short      cb_char16;
typedef int                 cb_int32;
typedef unsigned int        cb_uint32;
typedef unsigned int        cb_char32;
typedef long long           cb_int64;
typedef unsigned long long  cb_uint64;
typedef float               cb_float;
typedef double              cb_double;

#if CBASE_32_BIT
typedef cb_uint32           cb_size;
typedef cb_int32            cb_ssize;
#endif/*CBASE_32_BIT*/

#if CBASE_64_BIT
typedef cb_uint64           cb_size;
typedef cb_int64            cb_ssize;
#endif/*CBASE_32_BIT*/

#endif//CBASE_INTS_H
