/*
Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by this 
license (the "Software") to use, reproduce, display, distribute, execute, and 
transmit the Software, and to prepare derivative works of the Software, and to 
permit third-parties to whom the Software is furnished to do so, all subject to the 
following:

The copyright notices in the Software and this entire statement, including the 
above license grant, this restriction and the following disclaimer, must be 
included in all copies of the Software, in whole or in part, and all derivative 
works of the Software, unless such copies or derivative works are solely in the 
form of machine-executable object code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT 
HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER 
LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/**
 * \file memory.c
 * \date 2015
 */

/* PKG includes
 */
#include <cbase/memory.h>

/* STDLIB includes
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(_MSC_VER)
/*
 * On Windows, aligned APIs need malloc.h
 */
#include <malloc.h>
#include <Windows.h>
#endif/*defined(_MSC_VER)*/

#define ALIGN 64

void* cbase_allocate(cb_size sz)
{
#if defined(_MSC_VER)
    return _aligned_malloc(sz, ALIGN);
#else
    void* mem = NULL;
    int ret = posix_memalign(&mem, ALIGN, sz);
    (void)ret;
    return mem;
#endif
}

void cbase_deallocate(void* mem)
{
#if defined(_MSC_VER)
    _aligned_free(mem);
#else
    free(mem);
#endif
}

void* cbase_callocate(cb_size sz)
{
    void* p = cbase_allocate(sz);
    memset(p, 0, sz);
    return p;
}

#if CBASE_DEBUG

typedef struct malloc_info_t malloc_info;

struct malloc_info_t
{
   const cb_char*  file;
   int          line;
   cb_size       size;
   malloc_info* next;
   malloc_info* prev;
};

static malloc_info* S_HEAD;
static int          S_REG_EXIT = 0;

static
int cbase_dumpmem(void)
{
    malloc_info *mi = S_HEAD;
    int ret = 0;
    while (mi) {
        if ((int)(mi->size) >= 0) {
            ret = 1;
            printf("CBASE_LEAKED: %s (%4d): %8llu bytes at %p\n", mi->file, mi->line, (unsigned long long)mi->size, mi+1);
            fflush(stdout);
        }
        mi = mi->next;
    }
#if defined(CBASE_DEBUG_MEM_SHOW_ALL)
    mi = S_HEAD;
    while (mi) {
        if ((ptrdiff_t) mi->size < 0) {
            printf("CBASE_FREED : %s (%4d): %8llu bytes at %p\n", mi->file, mi->line, (unsigned long long)~mi->size, mi+1);
        }
        mi = mi->next;
    }
#endif/*defined(CBASE_DEBUG_MEM_SHOW_ALL)*/
    return ret;
}

void cbase_dumpmem_s(void)
{
    if (cbase_dumpmem()) { exit(1); }
}

void* cbase_allocate_debug(cb_size sz, const cb_char* file, int line)
{
    malloc_info *mi = (malloc_info*)cbase_allocate(sz + sizeof(*mi));
    if (mi == NULL) return mi;
    mi->file = file;
    mi->line = line;
    mi->next = S_HEAD;
    if (S_HEAD) {
        mi->next->prev = mi;
    } else if (!S_REG_EXIT) {
        atexit(cbase_dumpmem_s);
    }
    mi->prev = NULL;
    mi->size = (int)sz;
    S_HEAD = mi;
    return mi + 1;
}

void cbase_deallocate_debug(void *ptr)
{
    if (ptr != NULL) {
        malloc_info *mi = (malloc_info*)ptr - 1;
        mi->size = ~mi->size;
#if !defined(CBASE_DEBUG_MEM_SHOW_ALL)
        if (mi->prev == NULL) {
            assert(S_HEAD == mi);
            S_HEAD = mi->next;
        } else {
            mi->prev->next = mi->next;
        }
        if (mi->next) {
            mi->next->prev = mi->prev;
        }
#endif/*!defined(CBASE_DEBUG_MEM_SHOW_ALL)*/
   }
}

void* cbase_callocate_debug(cb_size sz, const cb_char* file, int line)
{
    void* p = cbase_allocate_debug(sz, file, line);
    memset(p, 0, sz);
    return p;
}

#endif/*CBASE_DEBUG*/
