/*
Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by this 
license (the "Software") to use, reproduce, display, distribute, execute, and 
transmit the Software, and to prepare derivative works of the Software, and to 
permit third-parties to whom the Software is furnished to do so, all subject to the 
following:

The copyright notices in the Software and this entire statement, including the 
above license grant, this restriction and the following disclaimer, must be 
included in all copies of the Software, in whole or in part, and all derivative 
works of the Software, unless such copies or derivative works are solely in the 
form of machine-executable object code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT 
HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER 
LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/**
 * \file memory.c
 * \date 2015
 */

/* PKG includes
 */
#include <cbase/memory.h>
#include <cbase/ints.h>

/* PKG INT includes
 */
#include "cbase/stdlib.h"

/* STDLIB includes
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>

void* cbase_allocate(cb_size sz)
{
    cb_uint8* mem = (cb_uint8*)malloc(sz + CBASE_MEM_ALIGN);
    cb_uint8* alignmem = (cb_uint8*)
        ((((cb_size)mem)/CBASE_MEM_ALIGN) * CBASE_MEM_ALIGN) + CBASE_MEM_ALIGN;
    *(alignmem - 1) = (alignmem - mem);
    return alignmem;
}

void* cbase_reallocate(void* m, cb_size newsize)
{
    cb_uint8* alignmem = m;
    cb_uint8* orig = (alignmem - *(alignmem - 1));
    cb_uint8* newmem = (cb_uint8*)realloc(orig, newsize + CBASE_MEM_ALIGN);
    alignmem = (cb_uint8*)
        ((((cb_size)newmem)/CBASE_MEM_ALIGN) * CBASE_MEM_ALIGN) + CBASE_MEM_ALIGN;
    *(alignmem - 1) = (alignmem - newmem);
    return alignmem;
}

void cbase_deallocate(void* m)
{
    cb_uint8* alignmem = m;
    free(alignmem - *(alignmem - 1));
}

void* cbase_callocate(cb_size sz)
{
    void* p = cbase_allocate(sz);
    memset(p, 0, sz);
    return p;
}

#if CBASE_DEBUG

typedef struct malloc_info_t malloc_info;

#define MALLOC_INFO_FIELDS \
   const cb_char*  file; \
   int             line; \
   int             size; \
   malloc_info*    next; \
   malloc_info*    prev  \

struct malloc_info_data_t
{
    MALLOC_INFO_FIELDS;
};

/* align correctly */
struct malloc_info_t
{
   MALLOC_INFO_FIELDS;
   char padding[
            (((sizeof(struct malloc_info_data_t)/CBASE_MEM_ALIGN)+1)*CBASE_MEM_ALIGN)
            - CBASE_MEM_ALIGN
               ];
};

static malloc_info* S_HEAD;
static int          S_REG_EXIT = 0;

static
int cbase_dumpmem(void)
{
    malloc_info *mi = S_HEAD;
    int ret = 0;
    while (mi) {
        if ((int)(mi->size) >= 0) {
            ret = 1;
            printf("CBASE_LEAKED: %s (%4d): %8llu bytes at %p\n", mi->file, mi->line, (unsigned long long)mi->size, mi+1);
            fflush(stdout);
        }
        mi = mi->next;
    }
#if defined(CBASE_DEBUG_MEM_SHOW_ALL)
    mi = S_HEAD;
    while (mi) {
        if ((ptrdiff_t) mi->size < 0) {
            printf("CBASE_FREED : %s (%4d): %8llu bytes at %p\n", mi->file, mi->line, (unsigned long long)~mi->size, mi+1);
        }
        mi = mi->next;
    }
#endif/*defined(CBASE_DEBUG_MEM_SHOW_ALL)*/
    return ret;
}

void cbase_dumpmem_s(void)
{
    if (cbase_dumpmem()) { exit(1); }
}

void* cbase_allocate_debug(cb_size sz, const cb_char* file, int line)
{
    malloc_info* mi = (malloc_info*)cbase_allocate(sz + sizeof(*mi));
    if (mi == NULL) return mi;
    mi->file = file;
    mi->line = line;
    mi->next = S_HEAD;
    if (S_HEAD) {
        mi->next->prev = mi;
    } else if (!S_REG_EXIT) {
        atexit(cbase_dumpmem_s);
        S_REG_EXIT = 1;
    }
    mi->prev = NULL;
    mi->size = (int)sz;
    S_HEAD = mi;
    return mi + 1;
}

void* cbase_reallocate_debug(void* ptr, cb_size sz, const cb_char* file, int line)
{
    if (ptr == NULL) {
        return cbase_allocate_debug(sz, file, line);
    } else if (sz == 0) {
        cbase_deallocate_debug(ptr);
        return NULL;
    } else {
        malloc_info* mi = (malloc_info*)ptr - 1;
        if (sz <= mi->size) {
            return ptr;
        } else {
#ifdef CBASE_REALLOC_PRESERVE_MALLOC_FILELINE
            void *q = cbase_allocate_debug(sz, mi->file, mi->line);
#else
            void *q = cbase_allocate_debug(sz, file, line);
#endif
            if (q) {
                memcpy(q, ptr, mi->size);
                cbase_deallocate_debug(ptr);
            }
            return q;
        }
    }
}

void cbase_deallocate_debug(void* ptr)
{
    if (ptr != NULL) {
        malloc_info* mi = (malloc_info*)ptr - 1;
        mi->size = ~mi->size;
#if !defined(CBASE_DEBUG_MEM_SHOW_ALL)
        if (mi->prev == NULL) {
            assert(S_HEAD == mi);
            S_HEAD = mi->next;
        } else {
            mi->prev->next = mi->next;
        }
        if (mi->next) {
            mi->next->prev = mi->prev;
        }
#endif/*!defined(CBASE_DEBUG_MEM_SHOW_ALL)*/
   }
}

void* cbase_callocate_debug(cb_size sz, const cb_char* file, int line)
{
    void* p = cbase_allocate_debug(sz, file, line);
    memset(p, 0, sz);
    return p;
}

#endif/*CBASE_DEBUG*/
