/*
Permission is hereby granted, free of charge, to any person or organization 
obtaining a copy of the software and accompanying documentation covered by this 
license (the "Software") to use, reproduce, display, distribute, execute, and 
transmit the Software, and to prepare derivative works of the Software, and to 
permit third-parties to whom the Software is furnished to do so, all subject to the 
following:

The copyright notices in the Software and this entire statement, including the 
above license grant, this restriction and the following disclaimer, must be 
included in all copies of the Software, in whole or in part, and all derivative 
works of the Software, unless such copies or derivative works are solely in the 
form of machine-executable object code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT 
HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER 
LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/**
 * \file utf8.c
 * \date 2015
 */

/* STDLIB includes
 */
#include <stdlib.h>

/* MOD includes
 */
#include <cbase/utf8.h>

#define UTF8_NUL   0x00
#define UTF16_NUL  0x0000
#define UTF32_NUL  0x00000000

CBASE_INLINE
cb_int8 utf8_num_follow_chars(cb_char ch)
{
    cb_uchar uc = ch;
    if (uc < 0x80) { return 0;  }
    if (uc < 0xC0) { return -1; }
    if (uc < 0xE0) { return 1;  }
    if (uc < 0xF0) { return 2;  }
    if (uc < 0xF5) { return 3;  }
    return -1;
}

CBASE_INLINE
cb_bool utf8_is_leading_byte(cb_char ch)
{
    return utf8_num_follow_chars(ch) != -1;
}

CBASE_INLINE
cb_bool utf8_is_continuation_byte(cb_char ch)
{
    return (*(cb_uchar*)(&ch) & 0x80) == 0x80;
}

/**
 * Return whether successful and assign string length and number of code points
 * in the string.
 */
cb_bool cb_utf8_count_codepts(const cb_char* str, cb_size* slen, cb_size* ncp)
{
    cb_int8 ntrailbytes = 0;
    cb_size len = 0;
    cb_size cp = 0;
    while (*str != UTF8_NUL) {
        ntrailbytes = utf8_num_follow_chars(*str);
        if (ntrailbytes == -1) { return CB_FALSE; }
        ++str;
        len += ntrailbytes + 1;
        while (ntrailbytes--) {
            if (!utf8_is_continuation_byte(*(str++))) { return CB_FALSE; }
        }
        ++cp;
    }
    if (slen) { *slen = len; }
    if (ncp)  { *ncp = cp; }
    return CB_TRUE;
}

CBASE_INLINE
cb_bool is_utf16_surr_leading(cb_char16 ch)
{
    return (0xD800 <= ch) && (ch <= 0xDBFF);
}

CBASE_INLINE
cb_bool is_utf16_surr_trailing(cb_char16 ch)
{
    return (0xDC00 <= ch) && (ch <= 0xDFFF);
}

/**
 * Return whether successful and assign string length and number of code points
 * in the string.
 */
cb_bool cb_utf16_count_codepts(const cb_char16* str, cb_size* slen, cb_size* ncp)
{
    cb_size len = 0;
    cb_size cp = 0;
    cb_char16 ch = 0;
    cb_bool prevsurr = CB_FALSE;
    while ((ch = *(str++)) != UTF16_NUL) {
        ++len;
        if (prevsurr) {
            if (!is_utf16_surr_trailing(ch)) { return CB_FALSE; }
            ++cp;
            prevsurr = is_utf16_surr_leading(ch);
        } else {
            if (is_utf16_surr_trailing(ch)) { return CB_FALSE; }
            if (is_utf16_surr_leading(ch)) { prevsurr = CB_TRUE;  continue; }
            ++cp;
            prevsurr = CB_FALSE;
        }
    }
    if (slen) { *slen = len; }
    if (ncp)  { *ncp = cp; }
    return CB_TRUE;
}


/**
 * Return whether successful and assign string length and number of code points
 * in the string.
 */
cb_bool cb_utf32_count_codepts(const cb_char32* str, cb_size* slen, cb_size* ncp)
{
    cb_size len = 0;
    while (*(str++) != UTF32_NUL) { ++len; }
    if (slen) { *slen = len; }
    if (ncp)  { *ncp = len; }
    return CB_TRUE;
}


/**
 * Return num code points read. The \p cp must always point to at least
 * two \c cb_char16 as surrogate pairs may be encountered.
 */
cb_uint8 cb_utf8_utf16_next(const cb_char** str, cb_char16* cp)
{
    return CB_FALSE;
}


/**
 * Return num code points read.The \p cp must always point to at least
 * one \c cb_char32.
 */
cb_uint8 cb_utf8_utf32_next(const cb_char** str, cb_char32* cp)
{
    return CB_FALSE;
}


/**
 * Return num code points read. The \p cp must always point to at least
 * six \c cb_char as multi-byte code points may be encountered.
 */
cb_uint8 cb_utf16_utf8_next(const cb_char16** str, cb_char* cp)
{
    return CB_FALSE;
}


/**
 * Return num code points read.The \p cp must always point to at least
 * six \c cb_char as multi-byte code points may be encountered.
 */
cb_uint8 cb_utf32_utf8_next(const cb_char32** str, cb_char* cp)
{
    return CB_FALSE;
}

/**
 *
 */
struct cb_utf8_utf16_cvt_tag
{
    cb_uint32 state;
};


/**
 *
 */
cb_utf8_utf16_cvt* cb_make_utf8_utf16_cvt()
{
    return NULL;
}


/**
 *
 */
void cb_destroy_utf8_utf16_cvt(cb_utf8_utf16_cvt* cvt)
{

}


/**
 *
 */
void cb_utf8_utf16_buffer(
        cb_utf8_utf16_cvt* cvt,
        const cb_char** src,
        cb_size* srclen,
        cb_char16** dst,
        cb_size* dstlen,
        cb_bool flush)
{

}

/**
 *
 */
struct cb_utf8_utf32_cvt_tag
{
    cb_uint32 state;
};

/**
 *
 */
cb_utf8_utf32_cvt* cb_make_utf8_utf32_cvt()
{
    return NULL;
}

/**
 *
 */
void cb_destroy_utf8_utf32_cvt(cb_utf8_utf32_cvt* cvt)
{

}


/**
 *
 */
void cb_utf8_utf32_buffer(
        cb_utf8_utf32_cvt* cvt,
        const cb_char** src,
        cb_size* srclen,
        cb_char32** dst,
        cb_size* dstlen,
        cb_bool flush)
{

}

/**
 *
 */
struct cb_utf16_utf8_cvt_tag
{
    cb_uint32 state;
};

/**
 *
 */
cb_utf16_utf8_cvt* cb_make_utf16_utf8_cvt()
{
    return NULL;
}


/**
 *
 */
void cb_destroy_utf16_utf8_cvt(cb_utf16_utf8_cvt* cvt)
{

}


/**
 *
 */
void cb_utf16_utf8_buffer(
        cb_utf16_utf8_cvt* cvt,
        const cb_char16** src,
        cb_size* srclen,
        cb_char** dst,
        cb_size* dstlen,
        cb_bool flush)
{

}

/**
 *
 */
struct cb_utf32_utf8_cvt_tag
{
    cb_uint32 state;
};


/**
 *
 */
cb_utf32_utf8_cvt* cb_make_utf32_utf8_cvt()
{
    return NULL;
}


/**
 *
 */
void cb_destroy_utf32_utf8_cvt(cb_utf32_utf8_cvt* cvt)
{

}


/**
 *
 */
void cb_utf32_utf8_buffer(
        cb_utf32_utf8_cvt* cvt,
        const cb_char32** src,
        cb_size* srclen,
        cb_char** dst,
        cb_size* dstlen,
        cb_bool flush)
{

}
